# Promtail 자체 포트 설정
server:
  http_listen_port: 9080 # promtail 자체 상태 확인용 (http://localhost:9080/targets)
  grpc_listen_port: 0 # 비활성화. promtail이 loki로 로그를 본래 떄는 HTTP를 사용한다.

# 로그 파일을 어디까지 읽었는지 기록하는 파일
positions:
  filename: /tmp/positions.yaml

# 로그를 보낼 Loki 주소
clients:
  - url: http://loki:3100/loki/api/v1/push

# 어떤 컨테이너의 로그를 수집할지
scrape_configs:
  - job_name: fastapi
    # 자동 감지 대신 로그 파일 경로 직접 지정
    static_configs:
      - targets:
          - localhost
        labels:
          job: fastapi
          container: fastapi-app
          # Docker가 컨테이너 로그를 저장하는 실제 경로
          __path__: /var/lib/docker/containers/*/*-json.log
    # Docker 로그가 JSON 형식으로 되어 있어서 파싱
    pipeline_stages:
      - json:
          expressions:
            log: log
            stream: stream
      # JSON에서 실제 로그 메세지만 추출
      - output:
          source: log
